### ISSUE TITLE
What is the meaning of 254 ?

### ISSUE THREAD

**Issue by LT-ZHONG** [HaoQChen/map_server#1]
Hi Chen,
Thanks for your code for the function `void mapCallback(const nav_msgs::OccupancyGridConstPtr& map)` in map_saver.cpp

![Selection_001](https://user-images.githubusercontent.com/49059253/100952872-51238100-354c-11eb-8a82-e103b9ecd8d2.png)

I want to ask what is the meaning of `fputc(254, out)`
Why the integer 254 is corresponding to free space while integer 000 corresponding to occupied space ?
Don't you think it is wired ? According to the picture below

![Selection_002](https://user-images.githubusercontent.com/49059253/100953291-41586c80-354d-11eb-8946-a34f68beea0f.png)

integer 000 should be corresponding to free space and integer 254 should be corresponding to occupied space.

**Comment by HaoQChen** [comment]
Hi Zhong, 254 is the color white, and 0 is black, 205 is grey. It is used to show in picture(which is saved by map_server), not about cost of passing the place
